local function read(path)
  local f=assert(io.open(path,"rb"));local s=f:read("*a");f:close();return s
end

local catalog=read("lib/ArenaCatalog.lua")
local builder=read("extract/ArenaBuilder.lua")
local pipeline=read("extract/BuildPipeline.lua")
local cache=read("lib/CacheManager.lua")
local native=read("lib/NativeLauncherCompat.lua")
local arena=read("lib/Arena.lua")
local settings=read("lib/BattleSettings.lua")

assert(catalog:find('id="relic_chamber",label="RELIC CHAMBER"',1,true),"Relic Chamber missing from arena catalog")
assert(catalog:find('{id="relic_chamber",label="RELIC CHAMBER"}',1,true),"Relic Chamber missing from arena selector options")
assert(settings:find('relic_chamber=true',1,true),"Relic Chamber rejected by battle settings")
assert(builder:find('sourceFsys="M3_shrine_1F_bf.fsys"',1,true),"Agate shrine battle FSYS is not source-backed")
assert(builder:find('sourceMember="M3_shrine_1F_bf.dat"',1,true),"Agate shrine battle DAT is not preferred")
assert(builder:find('textureRoot="cache/stages/relic_chamber/source"',1,true),"Relic Chamber source textures are not isolated")
assert(builder:find('g.texture={path=path,w=t.w,h=t.h,wrapS=t.wrapS,wrapT=t.wrapT,',1,true),"source GX wrap contract regressed")
assert(builder:find('coordinateMode=t.coordinateMode,colorMap=t.colorMap,alphaMap=t.alphaMap,blending=t.blending',1,true),"source texture coordinate/color state was discarded")
assert(native:find('"M3_shrine_1F_bf.fsys"',1,true),"native raw/CISO validation does not require shrine source")
assert(pipeline:find('cbe%-arena=10'),"arena migration identity was not bumped")
assert(pipeline:find('relic_chamber=GC6E01/M3_shrine_1F_bf.fsys/M3_shrine_1F_bf.dat/source%-hsd%-scene%-v33'),"pipeline marker does not bind Relic Chamber source")
assert(cache:find('cache/M3_shrine_1F_bf_cache.lua',1,true),"cache inspector does not require Relic Chamber")
assert(arena:find('profile=="relic"',1,true),"enclosed Relic Chamber backdrop guard missing")
assert(catalog:find('shotRadiusScale=0.60',1,true),"Relic Chamber source-shell camera radial contract missing")
assert(catalog:find('shotHeightScale=0.42',1,true),"Relic Chamber source-shell camera height contract missing")
assert(catalog:find('maxRadius=36',1,true) and catalog:find('maxY=13.5',1,true),"Relic Chamber source-shell camera volume missing")
assert(not catalog:find('cameraOccluderTrim=true',1,true),"legacy centre-ray Relic trim should stay disabled")
assert(arena:find('if activeDef and activeDef.profile=="relic" and activeDef.sourceShellOnly then return false end',1,true),"compensated source groups still pass through legacy Relic occlusion heuristics")
assert(builder:find('honorRenderPass=true,skipShadowMaterials=true',1,true),"Relic Chamber does not honor retail HSD render passes")
assert(catalog:find('sourceShellOnly=true,worldShell="source"',1,true),"Relic Chamber still uses synthetic forest-floor continuation")
assert(builder:find('honorRenderPass=true,skipShadowMaterials=true,nativeScaleCompensation=true',1,true),"Relic Chamber native joint scale compensation missing")
assert(builder:find('relic_chamber={sceneRadiusRaw=7800,maxGroupSpanRaw=20000,vertexRadiusRaw=7400}',1,true),"Relic Chamber source shell remains clipped")
-- Critical migration rule: adding one arena must not invalidate extractor/audio.
assert(pipeline:find('local B={cacheVersion=2,extractorRevision=15}',1,true),"Relic arena update unexpectedly invalidates global extraction cache")
assert(pipeline:find('arenasOnly=function',1,true),"arena-only migration path missing")
print("RelicChamberArenaTests PASS")
