local M=assert(loadfile('lib/TrainerMorph.lua'))({})
local clip={count=4,endFrame=2.5,joints={{{0,0,0}},{{2,4,6}},{{4,8,12}},{{5,10,15}}}}
local track={fps=30,roles={idle=clip,gesture=clip,reaction=clip}}
local _,a,b,u=M.trackSample(track,nil,.05)
assert(a==2 and b==3 and math.abs(u-.5)<1e-9)
local p=M.trackJoint(track,1,{nativeAge=.05})
assert(p[1]==3 and p[2]==6 and p[3]==9,'hand and mesh interpolation disagree')
local _,a,b,u=M.trackSample(track,'sendout',0,2,2)
assert(a==3 and b==4 and u==1,'fractional final frame skipped')
local _,a,b,u=M.trackSample(track,nil,2.5/30)
assert(a==1 and b==2 and u==0,'idle endpoint does not loop')
local _,_,_,_,role=M.trackSample(track,'defeat',0,.5,1)
assert(role=='reaction')
assert(M.trackSample(nil,nil,0)==nil)
print('Trainer native track interpolation tests passed')
